55 add toggle button to footer
nilsalm/satsuma pull request #59
Opened 2023-05-09 13:10 UTC by brokelyn

2023-05-10 09:42 UTC, nilsalm requested changes
Overall very nice and a lot of good changes!! I left some thought regarding the design and vibe, maybe we could change that but with limited time effort, let's get this merged soon after :)

2023-05-10 09:42 UTC, nilsalm commented on src/routes/templates/+page.svelte
> +<div class="p-4">
```suggestion
<div class="max-w-xl mx-auto mt-4 md:mt-8 mb-8 px-4">
```

2023-05-10 09:42 UTC, nilsalm commented on src/lib/components/Footer.svelte
> +			<FooterMainButton />
```suggestion
			<FooterButton icon={dummyIcon} href="/lists" />
			<FooterButton icon={dummyIcon} href="/templates" />
			<FooterMainButton />
			<FooterButton icon={dummyIcon} href="/categories" />
			<FooterButton icon={dummyIcon} href="/profile" />
```

2023-05-10 09:42 UTC, nilsalm commented on src/lib/components/Footer.svelte
> +			<FooterMainButton />
different order and main button in the middle

2023-05-10 09:42 UTC, nilsalm commented on src/lib/components/Item.svelte
> +			{/if}
I think the fat text here doesnt fit the light style of the rest of the app and makes for a weird dynamic in the navbar. I'd suggest skipping text altogether or having the text in much smaller font below the icon.

2023-05-10 09:42 UTC, nilsalm commented on src/lib/stores/mode.ts
> +export const isPlanModeActive = writable(false)
would this be possible to have as a mode that can be "planning" or "shopping" instead? Enum or type or something

2023-05-10 09:42 UTC, nilsalm commented on src/routes/lists/[listId]/+page.svelte
> +						<div in:fade out:fly={{ x: -25, duration: 200 }}>
Really nice, so smooth! Sadly on my screen it looks like i ticked off the wrong element, because the other elements are already move up in the list. See video below

2023-05-10 09:42 UTC, nilsalm requested changes
Overall very nice and a lot of good changes!! I left some thought regarding the design and vibe, maybe we could change that but with limited time effort, let's get this merged soon after :)

2023-05-11 07:07 UTC, brokelyn commented on src/routes/templates/+page.svelte
> +<div class="p-4">
at some point that should be put into a layout or component. Will add it for now

2023-05-11 07:10 UTC, brokelyn commented on src/lib/components/Item.svelte
> +			{/if}
What? Dont understand the point here. I just added a if statement nothing more

2023-05-11 07:12 UTC, brokelyn commented on src/lib/stores/mode.ts
> +export const isPlanModeActive = writable(false)
I would agree if we have more than two states but with only two states I think its fairly clear, isnt it? I would only result in importing the enum everywhere as well and have a longer condition eg. `appMode === AppStates.Planning`

2023-05-11 07:13 UTC, brokelyn commented on src/routes/lists/[listId]/+page.svelte
> +						<div in:fade out:fly={{ x: -25, duration: 200 }}>
yes have the issue as well. But this is not the scope of this issue. I will open another issue

2023-05-11 09:20 UTC, nilsalm commented on src/lib/components/Item.svelte
> +			{/if}
Yeah i must have put the comment in the wrong place, my bad! Will update

2023-05-11 09:57 UTC, nilsalm commented on src/lib/components/FooterMainButton.svelte
> +			<div class="text-gray-700 font-bold text-xl md:text-2xl">Shopping</div>
I meant to comment here: 

> I think the fat text here doesnt fit the light style of the rest of the app and makes for a weird dynamic in the navbar. I'd suggest skipping text altogether or having the text in much smaller font below the icon.

2023-05-11 09:57 UTC, nilsalm commented on src/lib/stores/mode.ts
> +export const isPlanModeActive = writable(false)
true, good point!

2023-05-11 11:19 UTC, merged